services:
  db:
    image: postgres:15
    container_name: booktracker-db
    restart: always
    env_file:
      - .env
    volumes:
      - booktracker-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi-backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env

volumes:
  booktracker-data:
